version: '3'

services:
  bitfinex_lending_bot:
    build: .
    restart: unless-stopped
    working_dir: /usr/src/app/
    environment:
      - BOT_jsonfile=www/botlog.json
      - BOT_jsonlogsize=200
      - BOT_startWebServer=true
    ports:
      - "8000:8000"
    volumes:
      - bitfinex_lending_bot-data:/usr/src/app/market_data
      - ./logs/botlog.json:/usr/src/app/www/botlog.json
      - ./default.cfg:/usr/src/app/default.cfg

volumes:
  bitfinex_lending_bot-data: